#!/bin/bash
# Generate PEP 503 simple repository indexes from the wheels published as GitHub
# release assets, one index per torch version+backend combo.
#
# Run from the www worktree: .scripts/gen_index.sh [output_dir]
#
# Wheels live on GitHub releases (not in this branch); each link points at the
# asset's download URL. Requires the `gh` CLI, authenticated for the repo.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="${1:-$(realpath "$SCRIPT_DIR/../whl")}"

REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)

# Site root (parent of the output dir) and the wheel dir's path relative to it,
# for the Jekyll landing page and its _data file. The landing page gets the
# published site URL from `site.github.url` (jekyll-github-metadata).
SITE_DIR=$(realpath "$(dirname "$OUT_DIR")")
OUT_REL=$(basename "$OUT_DIR")
DATA_FILE="$SITE_DIR/_data/wheels.yml"

# Every wheel asset across all releases, as "<name><TAB><download-url>".
mapfile -t ASSETS < <(
  gh api "repos/$REPO/releases" --paginate \
    --jq '.[].assets[] | select(.name | endswith(".whl")) | [.name, .browser_download_url] | @tsv'
)

if [ ${#ASSETS[@]} -eq 0 ]; then
  echo "No .whl release assets found on $REPO" >&2
  exit 1
fi

# Group assets by torch version+backend tag (e.g. torch2.9.cu12).
declare -A LINKS PYS
for line in "${ASSETS[@]}"; do
  name=${line%%$'\t'*}
  url=${line#*$'\t'}
  tag=${name#*+}; tag=${tag%%-cp*}; tag=${tag%%-py*}
  LINKS[$tag]+="<a href=\"$url\">$name</a>"$'\n'
  cp=$(grep -oE 'cp[0-9]+' <<<"$name" | head -1)
  [ -n "$cp" ] && PYS[$tag]+="${cp#cp}"$'\n'
done

for tag in "${!LINKS[@]}"; do
  pkg_dir="$OUT_DIR/$tag/torch-forced-align"
  mkdir -p "$pkg_dir"

  # Root index
  cat > "$OUT_DIR/$tag/index.html" <<'EOF'
<!DOCTYPE html>
<html><body>
<a href="torch-forced-align/">torch-forced-align</a>
</body></html>
EOF

  # Package index – wheels matching this tag
  {
    echo '<!DOCTYPE html>'
    echo '<html><body>'
    printf '%s' "${LINKS[$tag]}"
    echo '</body></html>'
  } > "$pkg_dir/index.html"

  echo "  $tag/" >&2
done

echo "Indexes generated in $OUT_DIR/ from $REPO release assets" >&2

# Emit a Jekyll data file the landing page (index.html) iterates over to link
# every per-combo index. Sorted newest torch first, backend ascending.
mkdir -p "$(dirname "$DATA_FILE")"
{
  echo "# Auto-generated by .scripts/gen_index.sh – do not edit by hand."
  echo "combos:"
  for tag in "${!LINKS[@]}"; do
    ver=${tag#torch}; ver=${ver%.*}
    backend=${tag##*.}
    printf '%s\t%s\t%s\n' "$ver" "$backend" "$tag"
  done | sort -t$'\t' -k1,1Vr -k2,2 | while IFS=$'\t' read -r ver backend tag; do
    # Python versions for this combo (cp310 -> 3.10), de-duplicated and sorted.
    pythons=$(printf '%s' "${PYS[$tag]}" | while read -r n; do echo "${n:0:1}.${n:1}"; done | sort -uV | paste -sd, -)
    echo "  - tag: \"$tag\""
    echo "    torch: \"$ver\""
    echo "    backend: \"$backend\""
    echo "    pythons: \"$pythons\""
    echo "    url: \"$OUT_REL/$tag/\""
  done
} > "$DATA_FILE"

echo "Wrote $DATA_FILE" >&2
