#!/bin/bash
# Generate PEP 503 simple repository indexes from wheels in a directory,
# one index per torch version+backend combo.
#
# Run from the www worktree: .scripts/gen_index.sh [wheel_dir] [output_dir]
#
# GitHub Pages doesn't serve Git LFS blobs, so wheel links point to the
# GitHub raw endpoint which does resolve LFS.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_WHL_DIR="$(realpath "$SCRIPT_DIR/../whl")"

WHL_DIR="${1:-$DEFAULT_WHL_DIR}"
OUT_DIR="${2:-$WHL_DIR}"

REPO_URL=$(git remote get-url origin | sed 's/\.git$//' | sed 's|git@github.com:|https://github.com/|')
BRANCH=$(git rev-parse --abbrev-ref HEAD)
# Relative path from repo root to wheel dir
WHL_REL=$(realpath --relative-to="$(git rev-parse --show-toplevel)" "$WHL_DIR")
RAW_BASE="$REPO_URL/raw/$BRANCH/$WHL_REL"

# Site root (parent of the output dir) and the path of the wheel dir relative to
# it, for the Jekyll landing page and its _data file. The landing page gets the
# published site URL from `site.github.url` (jekyll-github-metadata), so it is
# not emitted here.
SITE_DIR=$(realpath "$(dirname "$OUT_DIR")")
OUT_REL=$(basename "$OUT_DIR")
DATA_FILE="$SITE_DIR/_data/wheels.yml"

# Collect unique version tags from wheel filenames
declare -A TAGS
for whl in "$WHL_DIR"/*.whl; do
  [ -f "$whl" ] || continue
  filename=$(basename "$whl")
  tag=${filename#*+}
  tag=${tag%%-cp*}
  tag=${tag%%-py*}
  TAGS[$tag]=1
done

if [ ${#TAGS[@]} -eq 0 ]; then
  echo "No wheels found in $WHL_DIR" >&2
  exit 1
fi

for tag in "${!TAGS[@]}"; do
  pkg_dir="$OUT_DIR/$tag/torch-forced-align"
  mkdir -p "$pkg_dir"

  # Root index
  cat > "$OUT_DIR/$tag/index.html" <<'EOF'
<!DOCTYPE html>
<html><body>
<a href="torch-forced-align/">torch-forced-align</a>
</body></html>
EOF

  # Package index – only wheels matching this tag
  {
    echo '<!DOCTYPE html>'
    echo '<html><body>'
    for whl in "$WHL_DIR"/*+"$tag"-*.whl; do
      [ -f "$whl" ] || continue
      filename=$(basename "$whl")
      echo "<a href=\"$RAW_BASE/$filename\">$filename</a>"
    done
    echo '</body></html>'
  } > "$pkg_dir/index.html"

  echo "  $tag/" >&2
done

echo "Indexes generated in $OUT_DIR/ (links via $RAW_BASE)" >&2

# Emit a Jekyll data file the landing page (index.html) iterates over to link
# every per-combo index. Sorted newest torch first, backend ascending.
mkdir -p "$(dirname "$DATA_FILE")"
{
  echo "# Auto-generated by .scripts/gen_index.sh – do not edit by hand."
  echo "combos:"
  for tag in "${!TAGS[@]}"; do
    ver=${tag#torch}; ver=${ver%.*}
    backend=${tag##*.}
    printf '%s\t%s\t%s\n' "$ver" "$backend" "$tag"
  done | sort -t$'\t' -k1,1Vr -k2,2 | while IFS=$'\t' read -r ver backend tag; do
    # Python versions supported by this combo (cp310 -> 3.10), de-duplicated.
    pythons=$(
      for whl in "$WHL_DIR"/*+"$tag"-*.whl; do
        [ -f "$whl" ] || continue
        cp=$(basename "$whl" | grep -oE 'cp[0-9]+' | head -1)
        num=${cp#cp}
        echo "${num:0:1}.${num:1}"
      done | sort -uV | paste -sd, -
    )
    echo "  - tag: \"$tag\""
    echo "    torch: \"$ver\""
    echo "    backend: \"$backend\""
    echo "    pythons: \"$pythons\""
    echo "    url: \"$OUT_REL/$tag/\""
  done
} > "$DATA_FILE"

echo "Wrote $DATA_FILE" >&2
